### ISSUE TITLE
[Bug]: Recent changes to lspsaga integration doesn't work anymore

### ISSUE THREAD

**Issue by vunhatchuong** [philosofonusus/ecolog.nvim#2]
Since the recent change which switched from having a dedicated keymap to direct integrate I encounter this error for both `EcologSagaHover` and `EcologSagaGD`.

---

Error:

![image](https://github.com/user-attachments/assets/1b86925b-49d2-4688-a423-0cb2b28bdc1c)

---

Config:

```lua
return {
        "nvimdev/lspsaga.nvim",
        event = "LspAttach",
        -- stylua: ignore
        keys = {
            { "gd",         ":Lspsaga goto_definition<CR>",      desc = "[G]oto [D]definition" },
        },
        opts = function()
            local icons = require("core.icons")
            return {
                symbol_in_winbar = { enable = false },
                diagnostic = {
                    show_code_action = false,
                },
                finder = {
                    keys = { toggle_or_open = "<CR>" },
                },
                lightbulb = { sign = false },
            }
        end,
    },
    {
        "philosofonusus/ecolog.nvim",
        lazy = false,
        dependencies = {
            "nvim-telescope/telescope.nvim",
            "saghen/blink.cmp",
            "nvimdev/lspsaga.nvim",
        },
        opts = {
            path = Util.get_folder_location(),
            types = true,
            integrations = {
                lspsaga = true,
                blink_cmp = true,
                nvim_cmp = false,
                telescope = true,
            },
            shelter = {
                configuration = { partial_mode = true },
                modules = {
                    files = true,
                    peek = true,
                    telescope = true,
                    cmp = true,
                },
            },
        },
        config = function(_, opts)
            require("ecolog").setup(opts)
            require("telescope").load_extension("ecolog")
        end,
    },

```

**Comment by philosofonusus** [comment]
Hi, thanks for submitting the issue, I will certainly look it up. Sorry for inconvenience

**Comment by philosofonusus** [comment]
I have added a fix for the bug and unit tests to make sure that this doesn't happen in future. 
Please let me know if the issue is gone for you

**Comment by philosofonusus** [comment]
In the future I will pay more attention to such things and I'll start working now on tests!

**Comment by vunhatchuong** [comment]
Thank you so much for working on the plugin, I've been looking for this functionality for a while!

There are no more error messages this time. However, the docs mention that using `Lspsaga hover_doc` should show `Ecolog` s peek, but it doesn't; `Lspsaga goto_definition` and `EcologSagaHover` does as expected.

**Comment by philosofonusus** [comment]
I will look it up now

**Comment by philosofonusus** [comment]
I have added a fix for this issue, can you please verify it on your side?

**Comment by vunhatchuong** [comment]
Fixed! Thank you so much

**Comment by vunhatchuong** [comment]
@vunhatchuong Um sorry to bother you again but this introduce a bug for `Lspsaga finder`.

![image](https://github.com/user-attachments/assets/a8daea36-a9b4-43c0-9027-a317e5821ddd)

**Comment by philosofonusus** [comment]
Wow, sorry, looking into it 👀

**Comment by philosofonusus** [comment]
I have added a fix for this issue, please verify it on your side

**Comment by vunhatchuong** [comment]
Everything mentioned are fine now, thanks for fixing it so fast!
